name: Add artifacts to release

on:
  workflow_dispatch: # TODO: Remove when this is working
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
          - target: x86_64-pc-windows-gnu
          - target: x86_64-apple-darwin
          # TODO: How?
          # - target: aarch64-unknown-linux-musl
          # - target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          TOOLCHAIN_VERSION: 1.78.0
          ARCHIVE_TYPES: tar.gz zip
          EXTRA_FILES: LICENSE README.md sigi.1
